config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :reviews, only: [:create]

  end 

  devise_for :users
  resources :products

  resources :products do
    resources :reviews, only: [:create, :edit] do
      member do
        get 'like'
      end
    end
    member do
        get 'like'
    end
  end

  namespace :admin do
    resources :products
    resources :orders
    resources :users

    get '/', to: 'pages#index'
  end

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  mount_uploader :image, ImageUploader


	belongs_to :category
	has_many :reviews, dependent: :destroy
  	has_many :product_orders
  	has_many :orders, through: :product_orders

  	has_many :likes, as: :likeable
  	has_many :user_likes, through: :likes, source: :user

  	validates :name, presence: true
  	validates :description, presence: true
  	validates :price, presence: true
  	validates :stock, presence: true

    def remove_like (user)
      self.likes.where(user: user).first.delete      
    end

    def liked_by? (user)
      self.user_likes.include? user      
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :require_admin
  
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Product.all
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to @admin_product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_product }
      else
        format.html { render :edit }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_product_params
       params.require(:product).permit(:name, :description, :price, :stock, :category_id, :image, :image_cache, :remote_image_url, :remove_image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @reviews = @product.reviews.reverse
  end

  def like
      @product = Product.find(params[:id])
      @like = @product.likes.build(user: current_user)

      if @product.liked_by? current_user
        @product.remove_like current_user
        redirect_to @product, notice: 'Ok, ya no te gusta'
      elsif @product.save
        redirect_to @product, notice: 'Nos gusta que le guste'
      else
        redirect_to @product, notice: 'Intentalo de nuevo, tu like no quedo registrado'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock, :category_id, :image)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @admin_product]) do |f| %>
  <% if @admin_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @admin_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id, 'Categoria:' %>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: 'Elije una categoria' %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%#= f.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Admin Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_products.each do |admin_product| %>
      <tr>
        <td><%= admin_product.name %></td>
        <td><%= admin_product.description %></td>
        <td><%= admin_product.price %></td>
        <td><%= admin_product.category %></td>
        <td><%= admin_product.stock %></td>
        <td><%= link_to 'Show', admin_product_path(admin_product) %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(admin_product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Admin Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>